### ISSUE TITLE
Calling 'go get -u github.com/armored-dragon/go-imgui' returning errors.

### ISSUE THREAD

**Issue by sirkaiserkai** [Armored-Dragon/go-imgui#2] opened 2017-08-30 16:50 UTC
Hey,

calling `go get -u github.com/armored-dragon/go-imgui` returns the following errors.

```
$ go get -u github.com/armored-dragon/go-imgui
# github.com/armored-dragon/go-imgui
go/src/github.com/armored-dragon/go-imgui/imgui_wrap.cxx:2343:10: error: C-style cast from '__va_list_tag *' to 'va_list' (aka '__builtin_va_list') is not allowed
go/src/github.com/armored-dragon/go-imgui/imgui_wrap.cxx:2387:10: error: C-style cast from '__va_list_tag *' to 'va_list' (aka '__builtin_va_list') is not allowed
go/src/github.com/armored-dragon/go-imgui/imgui_wrap.cxx:2427:10: error: C-style cast from '__va_list_tag *' to 'va_list' (aka '__builtin_va_list') is not allowed
go/src/github.com/armored-dragon/go-imgui/imgui_wrap.cxx:2467:10: error: C-style cast from '__va_list_tag *' to 'va_list' (aka '__builtin_va_list') is not allowed
go/src/github.com/armored-dragon/go-imgui/imgui_wrap.cxx:2557:10: error: C-style cast from '__va_list_tag *' to 'va_list' (aka '__builtin_va_list') is not allowed
go/src/github.com/armored-dragon/go-imgui/imgui_wrap.cxx:2604:10: error: C-style cast from '__va_list_tag *' to 'va_list' (aka '__builtin_va_list') is not allowed
go/src/github.com/armored-dragon/go-imgui/imgui_wrap.cxx:7471:10: error: C-style cast from '__va_list_tag *' to 'va_list' (aka '__builtin_va_list') is not allowed
go/src/github.com/armored-dragon/go-imgui/imgui_wrap.cxx:7501:10: error: C-style cast from '__va_list_tag *' to 'va_list' (aka '__builtin_va_list') is not allowed
go/src/github.com/armored-dragon/go-imgui/imgui_wrap.cxx:7625:10: error: C-style cast from '__va_list_tag *' to 'va_list' (aka '__builtin_va_list') is not allowed
go/src/github.com/armored-dragon/go-imgui/imgui_wrap.cxx:7657:10: error: C-style cast from '__va_list_tag *' to 'va_list' (aka '__builtin_va_list') is not allowed
go/src/github.com/armored-dragon/go-imgui/imgui_wrap.cxx:8286:10: error: C-style cast from '__va_list_tag *' to 'va_list' (aka '__builtin_va_list') is not allowed
go/src/github.com/armored-dragon/go-imgui/imgui_wrap.cxx:14924:10: error: C-style cast from '__va_list_tag *' to 'va_list' (aka '__builtin_va_list') is not allowed
```

Using macOS Sierra 10.12.6 & go version go1.8.3 darwin/amd64

Appreciate any support.

**Comment by Armored-Dragon** [comment] 2017-08-31 05:29
This issue is basically a duplicate of #1. As I said there, I'll be looking into this. Been busy with another project the past few days.

**Closed by Armored-Dragon** 2017-08-31 05:29 UTC
